Don't patch Kernel using prepend:
- I have a very obscure bug that crashes YJIT when `Kernel.prepend`
  is called and I can only reproduce it in the context of Bundler.
  I can't reproduce it in a standalone script.

  The crash:

  ```
  thread '<unnamed>' (866962) panicked at ./yjit/src/codegen.rs:10857:9:
undefined optimized method!: nil?
stack backtrace:
   0:        0x10123e15c - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h5b9122f5e70f5951
   1:        0x101213134 - core::fmt::write::h6a8a2c9e4d999818
   2:        0x10123e6c0 - std::io::default_write_fmt::h89b6c507b2c6ffa7
   3:        0x10123ba00 - std::panicking::default_hook::{{closure}}::h24b4617c01d6581d
   4:        0x10123b8e8 - std::panicking::default_hook::h1955ee9a9845dfef
   5:        0x10123bcd8 - std::panicking::panic_with_hook::h8aad6dd2389d8f59
   6:        0x10123bb04 - std::panicking::panic_handler::{{closure}}::h3bd15449212d5b6e
   7:        0x10123b720 - std::sys::backtrace::__rust_end_short_backtrace::h3b25181b9f11fe05
   8:        0x10123a07c - __rustc[18f9140b322fd06e]::rust_begin_unwind
   9:        0x1012deba8 - core::panicking::panic_fmt::h900188084d4e95b5
  10:        0x10127e3c8 - yjit::codegen::reg_method_codegen::ha49d9454efcffa5f
                               at /Users/edouard/src/ruby-3.4.8/yjit/src/codegen.rs:10857:9
  11:        0x1012878b4 - yjit::codegen::yjit_reg_method_codegen_fns::hefdcd23393c050b8
                               at /Users/edouard/src/ruby-3.4.8/yjit/src/codegen.rs:10778:9
  12:        0x1012cd900 - rb_yjit_init
                               at /Users/edouard/src/ruby-3.4.8/yjit/src/yjit.rs:44:5
  13:        0x1010f374c - <unknown>
                               at ruby.c:1820:5
  14:        0x1010f2688 - <unknown>
                               at ruby.c:2215:13
  15:        0x1010f2688 - <unknown>
                               at ruby.c:2538:9
  16:        0x1010f2688 - <unknown>
                               at ruby.c:3174:12
  17:        0x100fdfd98 - <unknown>
                               at eval.c:117:16
  18:        0x100f24974 - <unknown>
                               at ./main.c:43:26
  19:        0x100f24974 - <unknown>
                               at ./main.c:68:12

thread '<unnamed>' (866962) panicked at library/core/src/panicking.rs:230:5:
panic in a function that cannot unwind
stack backtrace:
   0:        0x10123e15c - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h5b9122f5e70f5951
   1:        0x101213134 - core::fmt::write::h6a8a2c9e4d999818
   2:        0x10123e6c0 - std::io::default_write_fmt::h89b6c507b2c6ffa7
   3:        0x10123ba00 - std::panicking::default_hook::{{closure}}::h24b4617c01d6581d
   4:        0x10123b8e8 - std::panicking::default_hook::h1955ee9a9845dfef
   5:        0x10123bcd8 - std::panicking::panic_with_hook::h8aad6dd2389d8f59
   6:        0x10123badc - std::panicking::panic_handler::{{closure}}::h3bd15449212d5b6e
   7:        0x10123b720 - std::sys::backtrace::__rust_end_short_backtrace::h3b25181b9f11fe05
   8:        0x10123a07c - __rustc[18f9140b322fd06e]::rust_begin_unwind
   9:        0x1012dea14 - core::panicking::panic_nounwind_fmt::h7a4dae3ab8fc5259
  10:        0x1012de978 - core::panicking::panic_nounwind::h959d775d33fc4688
  11:        0x1012deb18 - core::panicking::panic_cannot_unwind::hda7331a7075802a1
  12:        0x1012cd918 - rb_yjit_init
                               at /Users/edouard/src/ruby-3.4.8/yjit/src/yjit.rs:42:1
  13:        0x1010f374c - <unknown>
                               at ruby.c:1820:5
  14:        0x1010f2688 - <unknown>
                               at ruby.c:2215:13
  15:        0x1010f2688 - <unknown>
                               at ruby.c:2538:9
  16:        0x1010f2688 - <unknown>
                               at ruby.c:3174:12
  17:        0x100fdfd98 - <unknown>
                               at eval.c:117:16
  18:        0x100f24974 - <unknown>
                               at ./main.c:43:26
  19:        0x100f24974 - <unknown>
                               at ./main.c:68:12
thread caused non-unwinding panic. aborting.
```

And the minimal reproduction steps are:

Write a small Gemfile
source "https://rubygems.org"

module C
end

Kernel.prepend(C)

2. Then run BUNDLER_SETUP="bundler/setup" ruby -e "1+1"